export const GIcons = {
  CaretLeft: require("../../assets/icons/global/caretLeft.png"),
  Checkbox: require("../../assets/icons/global/Checkbox.png"),
  CheckboxStart: require("../../assets/icons/global/CheckboxStart.png"),
  UnCheckbox: require("../../assets/icons/global/UnCheckbox.png"),
  notification: require("../../assets/icons/global/notification.png"),
  filter: require("../../assets/icons/global/filter.png"),
  CalendarDots: require("../../assets/icons/global/CalendarDots.png"),
  MapPin: require("../../assets/icons/global/MapPin.png"),
  HArrow: require("../../assets/icons/global/HArrow.png"),
  backArrow: require("../../assets/icons/global/backArrow.png"),
  uploadArrow: require("../../assets/icons/global/uploadArrow.png"),
  eyeOff: require("../../assets/icons/global/eyeOff.png"),
  eyeOpen: require("../../assets/icons/global/eyeOpen.png"),
};
